### ISSUE TITLE
Researcher in Bipedal Locomotion Interested in Testing: Question about casadi pkg-config build

### ISSUE THREAD

**Issue by grantgib** [alejandroastudillo/urdf2modelcasadi#15]
Hi Alejandro,

**Issue:** 
I am having trouble finding instructions for installing casadi with pkg-support. I have found some older issues on the github but just want to make sure I'm doing it right. Should I just follow the instructions on (https://github.com/casadi/casadi/wiki/InstallationLinux). If so I am not seeing a casadi/build/install_matlab directory which is needed for the configure.sh file.

-----
**Sidenote:**
I ran into your most recent publication and think that this could be really useful for some of my research. Would really like to give it a try with some of the bipedal robots that I work with. Right now we work with [FROST](https://github.com/ayonga/frost-dev) which uses the mathematica symbolics engine but I'm interested in seeing if casadi and pinocchio can generate faster c code.

**Comment by alejandroastudillo** [comment]
Hi Grant,

Yes, you should follow the instructions on [Installation Linux](https://github.com/casadi/casadi/wiki/InstallationLinux).
The latest versions of Casadi include pkg-support. If you install from source with the latest commit in Casadi you should be able to get pkg-support.

The `install_matlab` directory is a custom CMAKE_INSTALL_PREFIX I set, but you can just change it to the name you want.
From a build directory in a directory tree like this: 
```
            ├── casadi_source
            │   ├── casadi (from GitHub)
            │   ├── build
```
this is beside the casadi directory (cloned from GitHub), the cmake command I used was:
```
cmake -DWITH_COMMON=ON -DWITH_THREAD=ON -DWITH_IPOPT=ON  -DWITH_BLASFEO=ON -DCMAKE_INSTALL_PREFIX=install_matlab -DWITH_MATLAB=ON ../casadi
```
The important option here is the CMAKE_INSTALL_PREFIX option. If you set any other value there, you should also change it in the `configure.sh` file.

Let me know if it worked.

I'm sorry that the repository is not yet well organized. It was intended to be for personal use in the beginning, but now that we've seen a lot of potential in it we'll try to organize the code in this repository and make it easy for the users to compile and use it.

I hope this is useful for you. Let me know if you need some help and don't hesitate to contact me if there's any space for collaboration.
